apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: roboshop
    instanceTypes: ["m5.large", "c5.large", "t3.medium"]
    desiredCapacity: 2
    spot: true